import type { Provider, ProviderPriceRange } from "@/types";

export const mockProviders: Provider[] = [
  {
    slug: "dr-sarah-mensah",
    name: "Dr. Sarah Mensah",
    image: "/providers/dr-sarah-mensah.svg",
    specialty: "Endocrinology",
    subSpecialty: "Adult Diabetes Management",
    city: "Lusaka",
    country: "Zambia",
    bio: "Supports patients managing type 1 and type 2 diabetes with medication review, long-term care planning, and practical lifestyle guidance tailored to everyday routines.",
    consultationFee: 45,
    rating: 4.9,
    reviewCount: 124,
    isAvailable: true,
    yearsExperience: 11,
    languages: ["English", "French"],
    focusAreas: ["Insulin adjustment", "Type 2 diabetes", "Long-term care planning"],
    reviews: [
      {
        id: "sarah-review-1",
        author: "Martha K.",
        title: "Clear and reassuring",
        comment: "She explained my treatment plan in a way that felt calm, practical, and easy to follow.",
        rating: 5,
      },
      {
        id: "sarah-review-2",
        author: "Daniel P.",
        title: "Very structured follow-up",
        comment: "Appointments feel organized and I always leave knowing what I need to do next.",
        rating: 5,
      },
    ],
  },
  {
    slug: "dr-brian-okello",
    name: "Dr. Brian Okello",
    image: "/providers/dr-brian-okello.svg",
    specialty: "Diabetology",
    subSpecialty: "New Diagnosis Support",
    city: "Lusaka",
    country: "Zambia",
    bio: "Works closely with newly diagnosed patients to stabilize glucose management, simplify treatment plans, and build confidence around first-stage diabetes care.",
    consultationFee: 38,
    rating: 4.8,
    reviewCount: 89,
    isAvailable: true,
    yearsExperience: 8,
    languages: ["English", "Swahili"],
    focusAreas: ["New diagnoses", "Medication planning", "Lifestyle coaching"],
    reviews: [
      {
        id: "brian-review-1",
        author: "Alice T.",
        title: "Very approachable",
        comment: "He made the whole process feel less overwhelming and answered every question patiently.",
        rating: 5,
      },
      {
        id: "brian-review-2",
        author: "Jonathan M.",
        title: "Helpful first consultation",
        comment: "A strong first visit with realistic advice I could actually apply immediately.",
        rating: 4,
      },
    ],
  },
  {
    slug: "dr-anita-phiri",
    name: "Dr. Anita Phiri",
    image: "/providers/dr-anita-phiri.svg",
    specialty: "Nutrition",
    subSpecialty: "Clinical Nutrition for Diabetes",
    city: "Ndola",
    country: "Zambia",
    bio: "Guides patients through food planning, habit change, and nutrition strategies that align with glucose goals, medications, and sustainable routines.",
    consultationFee: 30,
    rating: 4.7,
    reviewCount: 67,
    isAvailable: false,
    yearsExperience: 7,
    languages: ["English"],
    focusAreas: ["Meal planning", "Weight management", "Nutrition routines"],
    reviews: [
      {
        id: "anita-review-1",
        author: "Ruth S.",
        title: "Practical nutrition advice",
        comment: "Her advice was specific, realistic, and much easier to maintain than generic meal plans.",
        rating: 5,
      },
      {
        id: "anita-review-2",
        author: "Grace L.",
        title: "Good long-term guidance",
        comment: "She helped me build better habits instead of giving a one-size-fits-all diet.",
        rating: 4,
      },
    ],
  },
  {
    slug: "dr-james-ncube",
    name: "Dr. James Ncube",
    image: "/providers/dr-james-ncube.svg",
    specialty: "Internal Medicine",
    subSpecialty: "Complex Chronic Care",
    city: "Lusaka",
    country: "Zambia",
    bio: "Treats patients with diabetes alongside hypertension, kidney risk, and other chronic conditions through coordinated, structured medical follow-up.",
    consultationFee: 52,
    rating: 4.8,
    reviewCount: 102,
    isAvailable: true,
    yearsExperience: 13,
    languages: ["English", "Bemba"],
    focusAreas: ["Complex chronic care", "Hypertension", "Kidney risk monitoring"],
    reviews: [
      {
        id: "james-review-1",
        author: "Chris N.",
        title: "Very thorough",
        comment: "He looked at the full picture and connected my diabetes care with my other health issues.",
        rating: 5,
      },
      {
        id: "james-review-2",
        author: "Mildred C.",
        title: "Confident clinical guidance",
        comment: "A detailed consultation with clear steps and good follow-up planning.",
        rating: 4,
      },
    ],
  },
  {
    slug: "dr-lucia-tembo",
    name: "Dr. Lucia Tembo",
    image: "/providers/dr-lucia-tembo.svg",
    specialty: "Pediatrics",
    subSpecialty: "Adolescent Diabetes Care",
    city: "Kitwe",
    country: "Zambia",
    bio: "Supports children and families managing diabetes with education, progress review, and age-appropriate care planning across each growth stage.",
    consultationFee: 41,
    rating: 4.9,
    reviewCount: 76,
    isAvailable: true,
    yearsExperience: 9,
    languages: ["English", "Nyanja"],
    focusAreas: ["Family support", "Adolescent care", "Education planning"],
    reviews: [
      {
        id: "lucia-review-1",
        author: "Parent of patient",
        title: "Excellent with families",
        comment: "She communicates clearly with both parents and children and makes the process feel manageable.",
        rating: 5,
      },
      {
        id: "lucia-review-2",
        author: "Janet R.",
        title: "Warm and organized",
        comment: "The visit felt compassionate and very well structured from start to finish.",
        rating: 5,
      },
    ],
  },
  {
    slug: "dr-peter-sitali",
    name: "Dr. Peter Sitali",
    image: "/providers/dr-peter-sitali.svg",
    specialty: "Cardiology",
    subSpecialty: "Diabetes and Heart Health",
    city: "Lusaka",
    country: "Zambia",
    bio: "Helps patients balance cardiovascular risk and diabetes management with prevention strategies, follow-up plans, and specialist insight.",
    consultationFee: 60,
    rating: 4.6,
    reviewCount: 54,
    isAvailable: false,
    yearsExperience: 12,
    languages: ["English"],
    focusAreas: ["Heart health", "Risk reduction", "Specialist review"],
    reviews: [
      {
        id: "peter-review-1",
        author: "Stephen A.",
        title: "Detailed cardiovascular review",
        comment: "He connected my diabetes management to my heart health in a way that made sense.",
        rating: 5,
      },
      {
        id: "peter-review-2",
        author: "Naomi B.",
        title: "Specialist insight",
        comment: "A useful consultation for understanding long-term risk and what to monitor next.",
        rating: 4,
      },
    ],
  },
];

export const providerPriceRanges: { label: string; value: ProviderPriceRange }[] = [
  { label: "All fees", value: "all" },
  { label: "Under $40", value: "under-40" },
  { label: "$40 to $50", value: "40-50" },
  { label: "Above $50", value: "above-50" },
];

export const providerSpecialties = ["All specialties", ...new Set(mockProviders.map((provider) => provider.specialty))];

export function getProviders() {
  return mockProviders;
}

export function getProviderBySlug(slug: string) {
  return mockProviders.find((provider) => provider.slug === slug);
}
