import type { Appointment } from "@/types";

export const mockPatientAppointments: Appointment[] = [
  {
    id: "apt-demo-brian-okello",
    providerId: "dr-brian-okello",
    providerName: "Dr. Brian Okello",
    providerSpecialty: "Diabetology",
    date: "2026-04-14",
    time: "09:30",
    status: "AWAITING_PAYMENT",
    paymentStatus: "AWAITING_PAYMENT",
    consultationFee: 38,
    createdAt: "2026-04-09T08:30:00.000Z",
  },
  {
    id: "apt-demo-sarah-mensah",
    providerId: "dr-sarah-mensah",
    providerName: "Dr. Sarah Mensah",
    providerSpecialty: "Endocrinology",
    date: "2026-04-20",
    time: "11:00",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    consultationFee: 45,
    createdAt: "2026-04-08T10:00:00.000Z",
  },
  {
    id: "apt-demo-james-ncube",
    providerId: "dr-james-ncube",
    providerName: "Dr. James Ncube",
    providerSpecialty: "Internal Medicine",
    date: "2026-04-02",
    time: "14:00",
    status: "COMPLETED",
    paymentStatus: "PAID",
    consultationFee: 52,
    createdAt: "2026-03-28T09:00:00.000Z",
  },
  {
    id: "apt-demo-anita-phiri",
    providerId: "dr-anita-phiri",
    providerName: "Dr. Anita Phiri",
    providerSpecialty: "Clinical Nutrition",
    date: "2026-03-30",
    time: "10:30",
    status: "CANCELLED",
    paymentStatus: "AWAITING_PAYMENT",
    consultationFee: 30,
    createdAt: "2026-03-20T15:15:00.000Z",
  },
  {
    id: "apt-demo-lucia-tembo",
    providerId: "dr-lucia-tembo",
    providerName: "Dr. Lucia Tembo",
    providerSpecialty: "Pediatrics",
    date: "2026-03-28",
    time: "08:45",
    status: "NO_SHOW",
    paymentStatus: "PAID",
    consultationFee: 41,
    createdAt: "2026-03-18T11:25:00.000Z",
  },
  {
    id: "apt-demo-peter-sitali",
    providerId: "dr-peter-sitali",
    providerName: "Dr. Peter Sitali",
    providerSpecialty: "Cardiology",
    date: "2026-04-18",
    time: "16:15",
    status: "REQUESTED",
    paymentStatus: "AWAITING_PAYMENT",
    consultationFee: 60,
    createdAt: "2026-04-12T13:45:00.000Z",
  },
];

export function getPatientAppointments() {
  return mockPatientAppointments;
}
